CREATE DATABASE contactos;

USE contactos;

CREATE TABLE usuarios (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(100) NOT NULL,
correo VARCHAR(70) NOT NULL,
clave VARCHAR(150) NOT NULL,
fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE contactos (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
usuario_id INT NOT NULL,
nombre VARCHAR(100) NOT NULL,
telefono VARCHAR(30) NOT NULL,
correo VARCHAR(60) NOT NULL,
fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE);


